export const ACCOUNTS_LOGIN_REQUEST = 'ACCOUNTS_LOGIN_REQUEST';
export const ACCOUNTS_LOGIN_SUCCESS = 'ACCOUNTS_LOGIN_SUCCESS';
export const ACCOUNTS_LOGIN_FAIL = 'ACCOUNTS_LOGIN_FAIL';
export const ACCOUNTS_LOGOUT = 'ACCOUNTS_LOGOUT';

export const ACCOUNTS_REGISTER_REQUEST = 'ACCOUNTS_REGISTER_REQUEST';
export const ACCOUNTS_REGISTER_SUCCESS = 'ACCOUNTS_REGISTER_SUCCESS';
export const ACCOUNTS_REGISTER_FAIL = 'ACCOUNTS_REGISTER_FAIL';

export const ACCOUNTS_VERIFY_OTP_REQUEST = 'ACCOUNTS_VERIFY_OTP_REQUEST';
export const ACCOUNTS_VERIFY_OTP_SUCCESS = 'ACCOUNTS_VERIFY_OTP_SUCCESS';
export const ACCOUNTS_VERIFY_OTP_FAIL = 'ACCOUNTS_VERIFY_OTP_FAIL';

export const ACCOUNTS_RESEND_OTP_REQUEST = 'ACCOUNTS_RESEND_OTP_REQUEST';
export const ACCOUNTS_RESEND_OTP_SUCCESS = 'ACCOUNTS_RESEND_OTP_SUCCESS';
export const ACCOUNTS_RESEND_OTP_FAIL = 'ACCOUNTS_RESEND_OTP_FAIL';